carts/urls.py
from django.conf.urls import url

from .views import (
cart_home,
cart_update)

urlpatterns = [
          url(r'^$',cart_home,name="home"),
          url(r'^update/',cart_update,name='update'),
          
           
      
      ]

ecommmerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url,include
from django.contrib import admin
from .views import home_page,about_page,contact_page,login_page,register_page
from django.views.generic import TemplateView

# from products.views import (ProductListView,
# product_list_view,
# ProducDetailView,product_detail_view,
# ProductFeaturedDetailView,
# ProductFeaturedListView,
# ProductDetailSlugView)

urlpatterns = [
    url(r'^about/',about_page,name='about'),
    url(r'^contact/',contact_page,name='contact'),
    url(r'^login/',login_page,name='login'),
  
      url(r'^cart/',include("carts.urls",namespace="cart")),
    url(r'^register/',register_page,name='register'),
    url(r'^products/',include("products.urls",namespace="products")),
        url(r'^bootstrap',TemplateView.as_view(template_name='bootstrap/example.html')),
        url(r'^search/',include("search.urls",namespace="search")),

#       url(r'^products/(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view()),
                  
#         url(r'^featured/(?P<pk>\d+)/$',ProductFeaturedDetailView.as_view()),

#      url(r'^featured',ProductFeaturedListView.as_view()),

#    # url(r'^products/(?P<pk>\d+)/$',ProducDetailView.as_view()),
#     url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),

#     url(r'^products/',ProductListView.as_view()),
#     url(r'^products-fbv/',product_list_view),

     url(r'^admin/', admin.site.urls),
    url('^$',home_page,name='home'),
  
   
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
ProductListView,
#product_list_view,
#ProducDetailView,product_detail_view,
#ProductFeaturedDetailView,
#ProductFeaturedListView,
ProductDetailSlugView)

urlpatterns = [
          url(r'^$',ProductListView.as_view(),name="list"),
          url(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(),name='detail'),
          
           
      
      ]

templates/base/css.html
{% load static %}
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- font awsesome for cart icon -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

templates/base/js.html
{% load static %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url%}
{% url 'products:list' as products_list_url%}
{% url 'login' as login_url%}
{% url 'register' as register_url%}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">


  <a class="navbar-brand" href="{{home_url}}">
    <img src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="" loading="lazy">
    {% if brand_name %} {{ brand_name }}{% else %}eCommerce {% endif %}
  </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item {% if request.path == home_url %}active {%endif%}">
          <a class="nav-link" href="{{home_url}}">Home </a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active {%endif%}">
          <a class="nav-link" href="{{contact_url}}">Contact </a>
        </li>
        <li class="nav-item {% if request.path == products_list_url %}active {%endif%}" >
          <a class="nav-link" href="{{products_list_url}}">Products </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == login_url %}active {%endif%}">
          <a class="nav-link " href="{{login_url}}" >Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == register_url %}active {%endif%}">
          <a class="nav-link " href="{{register_url}}" >Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active {%endif%}">
          <a class="nav-link " href="{{login_url}}" >Login</a>
        </li>
        {% endif %}

        <li class="nav-item {% if request.path == cart_url %}active {%endif%}">
          <a class="nav-link " href="{{cart_url}}" > {{ request.session.cart_itmes }} 
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          </a>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
      </ul>
     {% include 'search/snippets/search_form.html' %}
    </div>
  </div>
  </nav>